### ISSUE TITLE
og:image mistake

### ISSUE THREAD

**Issue by igoradamenko** [freetonik/freetonik.github.io#1]
Hi!

I think that [this line](https://github.com/freetonik/freetonik.github.io/blob/master/_includes/head.html#L32) of `_includes/head.html` is incorrect, 'cause on main page you have:

``` html
<meta property="og:image" content="/images/me.jpg | prepend: site.baseurl | prepend: site.url }}">
```

It seems like instead of `{{baseurl}}` you should use `{{site.baseurl}}` or something else, 'cause when page does not have `cover_url` `og:image`'s content is useless. 

I hope it helps :)

**Comment by freetonik** [comment]
Sorry, completely missed this. I fixed this later, thanks!
